Repository jenkinsci/custom-tools-plugin, pull requests merged in 2019-08, with the labels that each got.

#36 Upgrade to Jenkins 2.60.3 and Java 8
  pom.xml
  src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallWrapper.java
  src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionHelper.java
  src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionParameterDefinition.java
Labels: dependencies

#37 Enable Release Drafter for the plugin
  .github/release-drafter.yml
Labels: chore

#38 Enable automatic dependency updates for the repository
  .dependabot/config.yml
Labels: chore

#39 Move Plugin Documentation from Wiki to GitHub + documentation updates
  README.md
  docs/images/.gitkeep
  docs/images/buildWrapper.png
  docs/images/configure_tool.png
  docs/images/installLog.png
  docs/images/versions_Configuration.png
  docs/images/versions_Parameter.png
  docs/images/versions_ParameterDefinition.png
  docs/images/versions_usageInInstaller.png
Labels: documentation

#41 Fix typos in the documentation
  README.md
Labels: documentation

#40 Cleanup formatting in Jelly files
  src/main/resources/com/cloudbees/jenkins/plugins/customtools/CustomTool/config.jelly
  src/main/resources/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallWrapper/config.jelly
  src/main/resources/com/synopsys/arc/jenkinsci/plugins/customtools/LabelSpecifics/config.jelly
  src/main/resources/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionConfig/config.jelly
  src/main/resources/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionParameterDefinition/config.jelly
  src/main/resources/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionParameterDefinition/index.jelly
  src/main/resources/index.jelly
Labels: chore

#42 Minor code Improvements
  src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomTool.java
  src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallWrapper.java
  src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/EnvVariablesInjector.java
  src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/PathsList.java
  src/main/java/com/synopsys/arc/jenkinsci/plugins/customtools/versions/ToolVersionHelper.java
  src/main/java/jenkins/plugins/customtools/util/envvars/VariablesSubstitutionHelper.java
  src/test/java/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallWrapperTest.java
  src/test/java/com/cloudbees/jenkins/plugins/customtools/CustomToolInstallerTest.java
  src/test/java/com/synopsys/arc/jenkins/plugins/customtools/versions/ToolVersionParameterDefinitionTest.java
Labels: chore

#43 Update the license file to reference other contributors
  LICENSE
Labels: documentation, skip-changelog
